// Euler problem 12:
//
// The sequence of triangle numbers is generated by adding the natural numbers.
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
// The first ten terms would be:
//
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//
// Let us list the factors of the first seven triangle numbers:
//
//      1: 1
//      3: 1,3
//      6: 1,2,3,6
//     10: 1,2,5,10
//     15: 1,3,5,15
//     21: 1,3,7,21
//     28: 1,2,4,7,14,28
//
// We can see that 28 is the first triangle number to have over five divisors.
//
// What is the value of the first triangle number to have
// over five hundred divisors?

use crate::Runner;

pub struct Problem12;

impl Runner for Problem12 {
    fn id(&self) -> u32 {
        12
    }
    fn name(&self) -> &str {
        "First triangular number with over 500 divisors"
    }

    fn solve(&self) -> String {
        // Use an infinite range (1..) and map it to triangle numbers
        let result = (1u64..)
            .map(|n| n * (n + 1) / 2)
            .find(|&triangle| count_divisors(triangle) > 500)
            .unwrap();

        result.to_string()
    }
}

fn count_divisors(mut n: u64) -> u32 {
    let mut count = 1;

    while n % 2 == 0 {
        let mut exponent = 0;
        while n % 2 == 0 {
            exponent += 1;
            n /= 2;
        }
        count *= exponent + 1;
    }

    let mut d = 3;
    while d * d <= n {
        if n % d == 0 {
            let mut exponent = 0;
            while n % d == 0 {
                exponent += 1;
                n /= d;
            }
            count *= exponent + 1;
        }
        d += 2;
    }

    if n > 1 {
        count *= 2;
    }

    count
}
