#!/usr/bin/env python3

"""What is the 10 001st prime number?"""


def isPrime(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if (number % 2 == 0) or (number % 3 == 0):
        return False
    i = 5
    while (i ** 2) <= number:
        if (number % i == 0) or (number % (i + 2) == 0):
            return False
        i += 6

    return True


def euler_0007(n):
    """Find `count`th prime number."""

    count = 2
    num = 5
    while count < n:
        if isPrime(num):
            count += 1
        num += 2

    return num - 2


if __name__ == '__main__':
    print(f"Problem 0007: The 10001st prime number is: {euler_0007(10001)}")
