#!/usr/bin/env python3

"""
Euler problem 10:

The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.
"""


def euler_0010(limit):
    """
    limit: upper limits for the prime numbers to compute
    return: sum of the prime numbers found below the limit
    """
    marked = [0] * limit
    value = 3
    s = 2
    while value < limit:
        if marked[value] == 0:
            s += value
            i = value
            while i < limit:
                marked[i] = 1
                i += value
        value += 2
    return s


if __name__ == '__main__':
    """
    Find the sum of all the primes below limit.
    """
    print("Problem 0010: The sum of all the primes below 2 millions is: " +
          f"{euler_0010(2_000_000)}")
