#!/usr/bin/env python3

"""What is the smallest positive number that is evenly divisible by
 all of the numbers from 1 to 20?"""

from functools import reduce


def gcd(a: int, b: int) -> int:
    """Calculates the greatest common divisor (GCD) of two integers."""
    if b == 0:
        return a
    else:
        return gcd(b, a % b)


def lcm(a: int, b: int) -> int:
    """Calculates the least common multiple (LCM) of two integers."""
    return a * b // gcd(a, b)


def euler_0005(limit):
    return reduce(lcm, range(1, limit+1))


if __name__ == "__main__":
    print("Problem 0005: The smallest positive number that is divisible by " +
          f"all of the numbers up to 20: {euler_0005(20)}")
