#!/usr/bin/env python3

"""
Euler problem 12:

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have
over five hundred divisors?
"""


import argparse
import functools


def _primefactor(n):
    d = 2
    l = []
    c = 0
    while n>1:
        if not n % d:
            c += 1
            n /= d
            if n==1:
                l.append((d,c))
        else:
            if c>0:
                l.append((d,c))
            c = 0
            if d==2:
                d = 3
            else:
                d += 2
    return l


def _ndivs(n):
    l = _primefactor(n)
    return functools.reduce(lambda x,y: x*y,map(lambda x:x+1,[c for (d,c) in l]))


def pb12(n=500):
    k = 2
    while 1:
        tmp = k*(k+1)/2
        if _ndivs(tmp)>=n:
            break
        k += 1
    return tmp


#def find_divisors(number):
#    """
#    number: number to find the divisor of
#    return: number of divisors
#    """
#    divisors = list()
#    for i in range(1, int(number / 2) + 1):
#        if number % i == 0:
#            divisors.append(i)
#    divisors.append(number)
#    return divisors
#
#
#def find_triangle_number(divisors):
#    """
#    divisors: How many divisors we need to find
#    return: first triangle number with the required number
#            of divisors
#    """
#    start_from = int(divisors/2) ** 2
#    value = 1
#    increment = 2
#    while value < start_from:
#        value += increment
#        increment += 1
#    print("First number evaluated:", value)
#    how_many = 0
#    while how_many < divisors:
#        value += increment
#        increment += 1
#        how_many = len(find_divisors(value))
#    # print(find_divisors(value))
#    return value


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("divisors",
                        help="Number of divisors we're looking for",
                        type=int)
    args = parser.parse_args()
    print("Find the first triangle number to have over",
          args.divisors,
          "divisors")
    # print("Triangle Number:", find_triangle_number(args.divisors))
    print("Triangle Number:", pb12(args.divisors))
