#!/usr/bin/env python3

"""By considering the terms in the Fibonacci sequence whose values do not
 exceed four million, find the sum of the even-valued terms."""


def euler_0002(limit):
    """Return the sum of the even-valued terms."""
    total = 0
    first = 1
    second = 2
    while second < limit:
        if second % 2 == 0:
            total += second
        (first, second) = (second, first + second)

    return total


if __name__ == '__main__':
    print(
        "Problem 0002: Sum of even-valued fibonacci " +
        f"terms below 4000000 is: {euler_0002(4000000)}")
